// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpexfodveltykplhvfiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wZXhmb2R2ZWx0eWtwbGh2Zml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzQ4MjQsImV4cCI6MjA3NDcxMDgyNH0.leEJ_2mFoA8XzFTGDMf4MRN9Gcm4cTkR9njaI598zJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});